version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - cropvision-network

  backend:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    volumes:
      - ./ml-service/app:/app
    networks:
      - cropvision-network

networks:
  cropvision-network:
    driver: bridge

volumes:
  ml_models:
    driver: local